name:                bitcask-hs-example
version:             0.1.0.0
github:              "bronen/bitcask-hs-example"
license:             BSD-3-Clause
author:              "Brenno Rodrigues"
maintainer:          "brennopereira6@gmail.com"
copyright:           "2024 Brenno Rodrigues"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/bronen/bitcask-hs-example#readme>

dependencies:
- base >= 4.7 && < 5
- bitcask-hs
- curryer-rpc
- stm
- stm-containers
- winery
- bytestring
- utf8-string

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  bitcask-hs-example-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bitcask-hs-example

tests:
  bitcask-hs-example-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bitcask-hs-example
    - optparse-generic
